


import { AuthProvider } from '@/utils/context';



export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayoutt({
    children
}) {
    return (
        <html lang="en">
            <AuthProvider>
                <body>{children}</body>
            </AuthProvider>
        </html>
    )
}
